import * as path from "node:path";

export type CleanScope = "default" | "native";

export interface CleanPattern {
	/** Glob relative to the repo root. Matches directories as well as files. */
	readonly glob: string;
	readonly scope: CleanScope;
}

export interface CleanOptions {
	/** Also drop compiled native addons (`.node`), forcing a `build:native` rebuild. */
	readonly native?: boolean;
}

/**
 * Build output only. Everything listed here is either regenerated by a documented
 * `bun run <script>` or is a leftover an interrupted build left behind.
 *
 * `artifacts/` is deliberately absent: red-team/QA tests write evidence there and
 * read it back (`packages/coding-agent/src/tools/computer.enforcement.test.ts`,
 * `packages/tui/test/g0*-redteam.test.ts`). The directory is untracked (issue #4420);
 * test fixtures belong in packages/ test/ fixtures/.
 */
export const cleanPatterns: readonly CleanPattern[] = [
	{ glob: "packages/*/dist", scope: "default" },
	{ glob: "packages/*/dist-chrome", scope: "default" },
	{ glob: "packages/*/dist-firefox", scope: "default" },
	{ glob: "packages/coding-agent/binaries", scope: "default" },
	{ glob: "coverage", scope: "default" },
	{ glob: "packages/*/coverage", scope: "default" },
	// `bun build --compile` leaves these next to the entrypoint when interrupted.
	{ glob: "*.bun-build", scope: "default" },
	{ glob: "packages/*/*.bun-build", scope: "default" },
	{ glob: "*.tsbuildinfo", scope: "default" },
	{ glob: "packages/*/*.tsbuildinfo", scope: "default" },
	{ glob: "packages/natives/native/*.node", scope: "native" },
	{ glob: "packages/natives/native/*.node.build.json", scope: "native" },
];

/**
 * Paths whose removal would destroy installed dependencies, git state, session
 * state, or test evidence. A glob that resolves into one of these is a bug, so it
 * fails loudly instead of being silently skipped.
 */
const protectedSegments: ReadonlySet<string> = new Set([".git", ".gjc", "artifacts", "node_modules"]);

export function scopesFor(options: CleanOptions): ReadonlySet<CleanScope> {
	const scopes: CleanScope[] = ["default"];
	if (options.native) scopes.push("native");
	return new Set(scopes);
}

/** Reject anything that escapes the repo root or touches a protected path. */
export function assertRemovable(relativePath: string): string {
	const normalized = relativePath.replaceAll("\\", "/").replace(/^\.\//, "").replace(/\/+$/, "");
	const segments = normalized.split("/");
	if (
		normalized === "" ||
		normalized === "." ||
		normalized.startsWith("/") ||
		/^[A-Za-z]:\//.test(normalized) ||
		segments.some(segment => segment === "" || segment === "." || segment === "..")
	) {
		throw new Error(`clean-target-invalid: unsafe path '${relativePath}'`);
	}
	const protectedSegment = segments.find(segment => protectedSegments.has(segment));
	if (protectedSegment) {
		throw new Error(`clean-target-invalid: '${normalized}' is protected by '${protectedSegment}'`);
	}
	return normalized;
}

export async function resolveCleanTargets(root: string, options: CleanOptions = {}): Promise<string[]> {
	const scopes = scopesFor(options);
	const found = new Set<string>();
	for (const pattern of cleanPatterns) {
		if (!scopes.has(pattern.scope)) continue;
		const glob = new Bun.Glob(pattern.glob);
		for await (const entry of glob.scan({ cwd: root, onlyFiles: false, dot: true, followSymlinks: false })) {
			found.add(assertRemovable(entry));
		}
	}
	return Array.from(found).sort();
}

export function absoluteTarget(root: string, relativePath: string): string {
	const resolvedRoot = path.resolve(root);
	const target = path.resolve(resolvedRoot, assertRemovable(relativePath));
	if (!target.startsWith(`${resolvedRoot}${path.sep}`)) {
		throw new Error(`clean-target-invalid: '${relativePath}' escapes the repo root`);
	}
	return target;
}
